language: java
sudo: required

services:
  - docker
  
before_install:
  - docker pull openjdk:8

script:
  - docker build -t shamus03/connectfourserver .
  - docker run -it shamus03/connectfourserver bash -c 'ls /src'
