language: java
sudo: required

branches:
  only:
  - master

services:
  - docker
  
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker pull openjdk:8
  - docker pull openjdk:8-jre

script:
  - docker build -t shamus03/connectfourserver .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag shamus03/connectfourserver shamus03/connectfourserver:$TRAVIS_BUILD_NUMBER;
    docker push shamus03/connectfourserver;
    fi
